### ISSUE TITLE
[ BUG ] right calendar arrow button closes overlay (:

### ISSUE THREAD

**Issue by Libnus** [Libnus/polyplace#12]
**Describe the bug**
The right arrow button in the calendar overlay closes the overlay screen. Additionally, the arrows clickable areas seem to be way too wide.

**To Reproduce**
1. Go to reservations
2. Click on a free room
3. Click in the right and left arrows

**Expected behavior**
The right arrow button is mean to move the calendar to the next week of reservations not close the overlay.

**Desktop (please complete the following information):**
 - Browser: Safari v16.5
 - Version: 16.5

**Additional context**
It appears this has to do with the divs overlapping due to the position of the buttons being "fixed" but I haven't looked at this close enough yet. Height and width properties in the css don't seem to do anything making this seemingly simple bug a pain in the ---. At this point it must just be easier to rewrite the calendar bar entirely.

**Comment by louis-whatever** [comment]
Fixed as per [this commit](https://github.com/Libnus/polyplace/commit/f8be91ac522730e2c0322c51c285ec1fcede1952)
